package com.example.pos_driver.Model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CardData {
    private String sl_no;
    private String card_type;
    private String ksn;
    private String track2;
    private String pin;
    private String pan;
    private String processing_code;
    private String amount;
    private String transaction_date_time;
    private String stan;
    private String time;
    private String date;
    private String date_expiration;
    private String pos_entry_mode;
    private String pos_condition_code;
    private String card_acceptor_terminal_id;
    private String card_acceptor_id_code;
    private String card_acceptor_name_location;
    private String currency_code;
    private String receiving_institution_id_code;
    private String pos_data_code;
    private String switch_key;
    private String service_code;
    private String routing_info;
    private String auth_date_set;
    private String amt_tran_fee;
    private String amt_proc_fee;
    private String echo_data;
    private String msg_reason_code;
    private String pos_pin_capture_code;
    private String acquiring_institution_id_code;
    private String pos_data;
    private String auth_profile;
    private String pos_geo_data;
    private String sponsor_bank;
    private String card_seq_no;
    private boolean concat;
    private boolean white_space_xml;
    private String appendToICC;
    private int icFormatPost;
    private String ireq_amount_authorized;
    private String ireq_amount_other;
    private String ireq_application_identifier;
    private String ireq_application_interchange_profile;
    private String ireq_application_transaction_counter;
    private String ireq_application_usage_control;
    private String ireq_authorization_response_code;
    private String ireq_card_authentication_reliability_indicator;
    private String ireq_card_authentication_results_code;
    private String ireq_chip_condition_code;
    private String ireq_cryptogram;
    private String ireq_cry_info_data;
    private String ireq_customer_exc_data;
    private String ireq_cvm_list;
    private String ireq_cvm_results;
    private String ireq_form_factor_indicator;
    private String ireq_interface_device_serial_number;
    private String iac_default;
    private String iac_denial;
    private String iac_online;
    private String ireq_issuer_app_data;
    private String ireq_script_results;
    private String ireq_terminal_app_version_number;
    private String ireq_terminal_capabilities;
    private String ireq_terminal_country_Code;
    private String ireq_terminal_type;
    private String ireq_terminal_verification_result;
    private String ireq_transaction_category_code;
    private String ireq_transaction_currency_code;
    private String ireq_transaction_date;
    private String ireq_transaction_sequence_counter;
    private String ireq_transaction_type;
    private String ireq_unpredictable_number;
    private String resp_code;
    private String iresp_application_transaction_counter;
    private String iresp_card_authentication_results_code;
    private String iresp_issuer_authentication_data;
    private String iresp__issuer_script_template1;
    private String iresp_issuer_script_template2;
    private String iccDataString1;
}
